#
# Cleanup Drone Configuration
#
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.13-alpine
    commands:
      - go test
      - go build
      - /bin/sh scripts/gofmt.sh
    volumes:
      - name: dependencies
        path: /go
    environment:
      CGO_ENABLED: 0

  - name: build
    image: golang:1.13-alpine
    commands: go build
    volumes:
      - dependencies
      - path: /go

volumes:
  - name: dependencies
    temp:
      {}

trigger:
  branch:
    - drone