#
# Cleanup Drone Configuration
#
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.13-alpine
    commands:
      - go test
      - go build
      - /bin/bash scripts/gofmt.sh
    volumes:
      - name: dependencies
        path: /go
    environment:
      CGO_ENABLED: 0

volumes:
  - name: dependencies
    temp:
      {}

trigger:
  branch:
    - drone