version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.13
        environment:
          CGO_ENABLED: 0
          GO111MODULE: "on"

  github-container:
    docker:
      - image: cibuilds/github:0.10

jobs:
  cleanup-test:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - go-mod-v1-{{ .Branch }}-
            - go-mod-v1-
            - git-v1-{{ .Branch }}-{{ .Revision }}
            - git-v1-{{ .Branch }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg
      - save_cache:
          key: git-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: make test

  cleanup-build:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - go-mod-v1-{{ .Branch }}-
            - go-mod-v1-
            - git-v1-{{ .Branch }}-{{ .Revision }}
            - git-v1-{{ .Branch }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg
      - save_cache:
          key: git-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: Build the cleanup binary
          command: make build
      - persist_to_workspace:
          root: .target
          paths:
            - cleanup

  gh-release:
    executor: github-container
    steps:
      - attach_workspace:
          at: /tmp/.target
      - run:
          name: Publish GitHub release
          command: |
            VERSION=$(cleanup --quiet version)
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -delete ${VERSION} ./artifacts/

workflows:
  version: 2
  cleanup-ci:
    jobs:
      - cleanup-build
      - cleanup-test:
          requires:
            -  cleanup-build
      - gh-release:
          requires:
            - cleanup-build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/