#
# Cleanup CircleCI 2.1 Configuration
#
# This CI pipeline is capable of validating the code, running unit
# tests and - if the workflow has been triggered by a tag - building
# binaries for all supported platforms, creating a GitHub release as
# well as publishing a corresponding Docker image to Docker Hub.
#
version: 2.1

executors:
  go-container:
    docker:
      - image: circleci/golang:1.13
        environment:
          CGO_ENABLED: 0
          G111MODULE: "on"

jobs:
  cleanup-test:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - dependency-cache-v1-{{ .Branch }}-
            - dependency-cache-v1-
            - repository-cache-v1-{{ .Branch }}-{{ .Revision }}
            - repository-cache-v1-{{ .Branch }}-
            - repository-cache-v1-
      - run: go mod download
      - save_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg
      - save_cache:
          key: repository-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run:
          name: Check Go format
          command: "! go fmt ./... | read"
      - run:
          name: Run all tests
          command: go test -v ./...

  cleanup-build-releases:
    executor: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - dependency-cache-v1-{{ .Branch }}-
            - dependency-cache-v1-
            - repository-cache-v1-{{ .Branch }}-{{ .Revision }}
            - repository-cache-v1-{{ .Branch }}-
            - repository-cache-v1-
      - run: go mod download
      - save_cache:
          key: dependency-cache-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg
      - save_cache:
          key: repository-cache-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: mkdir -p /tmp/artifacts
      - run:
          name: Build and pack Cleanup for Linux
          command: |
            GOOS=linux GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o .target/cleanup main.go
            cp .target/cleanup cleanup
            tar -czf /tmp/artifacts/cleanup-linux-amd64.tar.gz cleanup
      - run:
          name: Build and pack Cleanup for macOS
          command: |
            GOOS=darwin GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o .target/cleanup main.go
            cp .target/cleanup cleanup
            tar -czf /tmp/artifacts/cleanup-macos-amd64.tar.gz cleanup
      - run:
          name: Build and pack Cleanup for Windows
          command: |
            GOOS=windows GOARCH=amd64 go build -v -ldflags "-X main.version=${CIRCLE_TAG}" \
              -o .target/cleanup.exe main.go
            cp .target/cleanup.exe cleanup.exe
            zip /tmp/artifacts/cleanup-windows-amd64.zip cleanup.exe
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - cleanup-linux-amd64.tar.gz
            - cleanup-macos-amd64.tar.gz
            - cleanup-windows-amd64.zip

  cleanup-release-gh:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/artifacts
      - run: mkdir artifacts && cp /tmp/artifacts/* artifacts/
      - run:
          name: Publish GitHub release
          command: |
            ghr -t "${GITHUB_TOKEN}" \
                -u "${CIRCLE_PROJECT_USERNAME}" \
                -r "${CIRCLE_PROJECT_REPONAME}" \
                -c "${CIRCLE_SHA1}" \
                -delete "${CIRCLE_TAG}" \
                artifacts/

  cleanup-release-docker:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Log in to Docker Hub
          command: |
            echo ${DOCKER_PASS} | docker login --username ${DOCKER_USER} --password-stdin
      - run:
          name: Build the Docker image (Light)
          command: |
            docker image build --build-arg VERSION=${CIRCLE_TAG} -t dominikbraun/cleanup:${CIRCLE_TAG} .
      - run:
          name: Tag the Docker image (Light) as latest
          command: |
            docker image tag dominikbraun/cleanup:${CIRCLE_TAG} dominikbraun/cleanup:latest
      - run:
          name: Publish the Docker images (Light)
          command: |
            docker push dominikbraun/cleanup:${CIRCLE_TAG}
            docker push dominikbraun/cleanup:latest

workflows:
  version: 2
  cleanup-ci:
    jobs:
      - cleanup-test:
          filters:
            tags:
              only: /.*/
      - cleanup-build-releases:
          requires:
            - cleanup-test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - cleanup-release-gh:
          requires:
            - cleanup-build-releases
          filters:
            tags:
              only: /.*/
      - cleanup-release-docker:
          requires:
            - cleanup-release-gh
          filters:
            tags:
              only: /.*/